#!/bin/sh

echo "> Stopping wireguard service"

if [ -f /etc/wireguard/wg0.conf ]; then
    echo "> WireGuard config file exists, stopping WireGuard service"
    wg-quick down wg0
else
    echo "> WireGuard config file does not exist, skipping WireGuard service stop"
fi
