#!/bin/sh

echo "> Starting wireguard service"

if [ ! -f /etc/wireguard/wg0.conf ]; then
    echo "> Waiting for WireGuard config to be written..."
    while [ ! -f /etc/wireguard/wg0.conf ]; do
        sleep 2
    done
fi

# Bring up the WireGuard interface
wg-quick up wg0

# Monitor the status of the WireGuard interface (wg0)
while ip link show wg0 2>/dev/null | grep -q "state"; do
    sleep 5
done
